name: Publish Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - run: composer install --no-dev --prefer-dist
      
      - uses: packagist/action@v1
        with:
          package_name: screenshotmax/sdk
          api_token: ${{ secrets.PACKAGIST_TOKEN }}
