name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpunit

      - run: composer install --no-interaction --working-dir=.
      - run: phpunit -c phpunit.xml